# Generated by Django 2.2.16 on 2022-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220616_1308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_cat_name_slug',
        ),
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_genre_name_slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
